version: '3'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: mantenimientos-docker
    ports:
      - 8080:80
    volumes:
      - .:/srv/app
    links:
      - mysql
    environment:
      DB_HOST: mysql
      DB_DATABASE: dbpistongps
      DB_USERNAME: mant
      DB_PASSWORD: password
  mysql:
    image: mysql:5.7
    ports:
      - 13306:3306
    volumes:
      - ./.docker/mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: dbpistongps
      MYSQL_USER: mant
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
